<?php
// @codingStandardsIgnoreFile
?>
<div class="actions actions-get-auth-token">
    <div id="auth_token_result" class="message-validation hide"></div>
    <button class="action-validate-get-auth-token sage-button-callback <?php echo $block->getAddClass();?>" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span id="span-for-active-button"><?php /* @escapeNotVerified */
            echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<style>
    .callback-actived {
        background-color: #99ff99 !important;
        border: 1px white solid !important;
        cursor: default;
        pointer-events: none;
    }
</style>
<script>
    require(['jquery'], function ($) {
        $('#check_sage_api_button').click(function () {
            $.ajax({
                type: "GET",
                url: '<?= $block->getUrl('sagepay/system_config/checkApi'); ?>',
                showLoader: true,
                success: function (response) {
                    console.log(response);
                    var result_token = $('#auth_token_result');
                    if (response.success) {
                        $("span#span-for-active-button").html("Api working");
                        $('button.action-validate-get-auth-token.sage-button-callback').addClass("callback-actived");
                        alert("Api working");
                    }
                    if (response.error) {
                        $("span#span-for-active-button").html("Api error");
                        alert("Error");
                    }
                }
            });
        });

    });
</script>