<?php
/**
 * Created by Magenest.
 * Author: Pham Quang Hau
 * Date: 07/08/2016
 * Time: 14:39
 */
/** @var \Magenest\SagePay\Block\Adminhtml\Order\View\Info\Transaction $block */
$transaction = $block->getTransaction();
?>

<br><br>
<div class="admin__page-section-item">
    <div class="admin__page-section-item-title">
        <span class="title">SagePay Transaction Detail</span>
    </div>
    <div class="admin__page-section-item">
        <table class="data-table admin__table-secondary">
            <tbody>
            <?php if ($transaction->getId()) { ?>
                <tr>
                    <td>Transaction ID</td>
                    <td><?php echo $transaction->getData('transaction_id');?></td>
                </tr>
                <tr>
                    <td>Transaction Status</td>
                    <td><?php echo $transaction->getData('transaction_status'); ?></td>
                </tr>
                <tr>
                    <td>3D Secure Check</td>
                    <td><?php echo $transaction->getData('card_secure'); ?></td>
                </tr>
                <tr>
                    <td>Transaction Detail</td>
                    <td><?php echo $transaction->getData('status_detail'); ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

    </div>
</div>
