<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Form\Cc $block
 */

// @codingStandardsIgnoreFile
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$code = $block->escapeHtml($block->getMethodCode());
$controller = $block->escapeHtml($block->getRequest()->getControllerName());
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');

?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?php /* @noEscape */ echo $code; ?>"
          style="display:none;">
    <div class="admin__field _required">
        <label for="<?php /* @noEscape */ echo $code; ?>_cc_name" class="admin__field-label">
            <span><?php echo $block->escapeHtml(__('Credit Card Holder Name')); ?></span>
        </label>

        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */ echo $code; ?>_cc_name"
                   name="payment[cc_name]"
                   class="input-text required-entry admin__control-text" />
        </div>
    </div>
    <div class="admin__field _required">
        <label for="<?php /* @noEscape */ echo $code; ?>_cc_number" class="admin__field-label">
            <span><?php echo $block->escapeHtml(__('Credit Card Number')); ?></span>
        </label>

        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */ echo $code; ?>_cc_number"
                   name="payment[cc_number]"
                   class="input-text required-entry validate-cc-number admin__control-text"
                   value="<?php /* @noEscape */ echo $block->getInfoData('cc_number'); ?>"/>
        </div>
    </div>
    <div class="admin__field _required">
        <label for="<?php /* @noEscape */ echo $code; ?>_expiration" class="admin__field-label">
            <span><?php echo $block->escapeHtml(__('Expiration Date')); ?></span>
        </label>

        <div class="admin__field-control">
            <select id="<?php /* @noEscape */ echo $code; ?>_expiration"
                    name="payment[cc_exp_month]"
                    class="validate-cc-exp required-entry admin__control-select admin__control-select-month">
                <?php foreach ($block->getCcMonths() as $k => $v): ?>
                    <option value="<?php echo $block->escapeHtml($k); ?>"
                            <?php if ($k == $ccExpMonth): ?>selected="selected"<?php endif; ?>>
                        <?php echo $block->escapeHtml($v); ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <select id="<?php /* @noEscape */ echo $code; ?>_expiration_yr"
                    name="payment[cc_exp_year]"
                    class="required-entry admin__control-select admin__control-select-year">
                <?php foreach ($block->getCcYears() as $k => $v): ?>
                    <option value="<?php /* @noEscape */ echo $k ? $block->escapeHtml($k) : ''; ?>"
                            <?php if ($k == $ccExpYear): ?>selected="selected"<?php endif; ?>>
                        <?php echo $block->escapeHtml($v); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <?php if ($block->hasVerification()): ?>
        <div class="admin__field _required field-cvv">
            <label for="<?php /* @noEscape */ echo $code; ?>_cc_cid" class="admin__field-label">
                <span><?php echo $block->escapeHtml(__('Card Verification Number')); ?></span>
            </label>

            <div class="admin__field-control">
                <input type="text"
                       class="required-entry input-text validate-cc-cvn admin__control-text"
                       id="<?php /* @noEscape */ echo $code; ?>_cc_cid" name="payment[cc_cid]"
                       value="<?php /* @noEscape */ echo $block->getInfoData('cc_cid') ?>"/>
            </div>
        </div>
    <?php endif; ?>
</fieldset>

<script>
    require([
        'prototype',
        'Magento_Sales/order/create/scripts',
        'Magento_Sales/order/create/form'
    ], function(){
        /**
         * Disable card server validation in admin
         */
        order.addExcludedPaymentMethod('<?= /* @noEscape */ $code ?>');
    });
</script>

